"""Add ChatHistory table

Revision ID: 671c1773dbbc
Revises: 03cefe8e8ed8
Create Date: 2025-07-29 17:11:28.616174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671c1773dbbc'
down_revision = '03cefe8e8ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history')
    # ### end Alembic commands ###
