"""Add volunteer table

Revision ID: d126bc13e66d
Revises: 2a2f61eedc62
Create Date: 2025-07-28 14:41:57.183827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd126bc13e66d'
down_revision = '2a2f61eedc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('available_days', sa.String(length=100), nullable=False),
    sa.Column('available_times', sa.String(length=100), nullable=False),
    sa.Column('last_assigned', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer')
    # ### end Alembic commands ###
